import { StyleSheet, Dimensions } from "react-native";
import { hexToRgb } from "../../services/helperFunctions";

import fonts from "../../theme/fonts";

const { height } = Dimensions.get("screen");
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  scrollContainer: {
    flexGrow: 1,
    paddingTop: 10,
  },
  logoutBtn: {
    paddingVertical: 20,
    marginHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "#D1D1D1",
  },
  logoutBtnTxt: (color) => ({
    fontSize: 18,
    marginLeft: 20,
    color: color || "#062D5B",
    fontFamily: fonts.Bold_Font,
    textTransform: "uppercase",
  }),
  iconStyle: (color) => ({
    height: 25,
    width: 25,
    tintColor: color || "#062D5B",
  }),
  modalContainer: {
    flex: 1,
    justifyContent: "flex-end",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
  },
  modalDataContainer: {
    maxHeight: height * 0.75,
    paddingVertical: 20,
    paddingHorizontal: 20,
    borderTopEndRadius: 20,
    backgroundColor: "#fff",
    borderTopStartRadius: 20,
  },
  reasonTxt: (color) => ({
    color,
    fontSize: 16,
    lineHeight: 19,
    marginLeft: 10,
    paddingVertical: 5,
    fontFamily: fonts.Medium_Font,
  }),
  modalButtonContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
  },
  submitBtn: (color) => ({
    height: 40,
    width: 110,
    borderRadius: 5,
    marginHorizontal: 15,
    alignItems: 'center',
    justifyContent: "center",
    backgroundColor: color || "#5086A7",
  }),
  submitBtnTxt: {
    fontFamily: fonts.Medium_Font,
    fontSize: 14,
    lineHeight: 16,
    letterSpacing: 1,
    color: "#FFFFFF",
  },
  clearBtnTxt: {
    fontFamily: fonts.Medium_Font,
    fontSize: 14,
    lineHeight: 16,
    letterSpacing: 1,
    color: "#7E7E7E",
  },
  clearBtn: {
    height: 40,
    width: 110,
    borderWidth: 1,
    borderRadius: 5,
    marginHorizontal: 15,
    alignItems: 'center',
    borderColor: "#D1D1D1",
    justifyContent: "center",
  },
  deleteModalTitle: (color) => ({
    color,
    fontSize: 22,
    lineHeight: 26,
    letterSpacing: 1,
    marginBottom: 10,
    textAlign: "center",
    fontFamily: fonts.Bold_Font,
  }),
  selectBtn: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
  },
  nameContainer: (backgroundColor) => ({
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    padding: 20,
    backgroundColor,
    alignItems: "center",
    justifyContent: "center",
    borderBottomStartRadius: 20,
    borderBottomEndRadius: 20,
  }),
  triangle: (borderBottomColor) => ({
    position: "absolute",
    bottom: -30,
    width: 0,
    height: 0,
    backgroundColor: "transparent",
    borderStyle: "solid",
    borderLeftWidth: 15,
    borderRightWidth: 15,
    borderBottomWidth: 30,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderBottomColor,
    transform: [{ rotate: "180deg" }],
  }),
  nameText: {
    fontSize: 26,
    color: "#fff",
    lineHeight: 30,
    textAlign: "center",
    fontFamily: fonts.Bold_Font,
    textTransform: "uppercase",
  },
  inputBox: {
    marginHorizontal: 30,
  },
  inputLabel: (color) => ({
    color: color || '#062D5B',
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 10,
    marginLeft: 5,
    marginTop: 15,
  }),
  inputContainer: {
    flexDirection: 'row',
    alignItems: "center",
  },
  loginIcons: (color) => ({
    padding: 15,
    borderWidth: 2,
    borderRadius: 10,
    overflow: "hidden",
    borderColor: 'white',
    backgroundColor: color || '#062D5B',
  }),
  inputs: (color) => ({
    fontSize: 14,
    fontFamily: fonts.Regular_Font,
    color: color || "#062D5B",
    borderWidth: 1,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    borderStartColor: 'transparent',
    borderColor: '#D1D1D1',
    padding: 15,
    flex: 1,
  }),
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 15,
    alignSelf: "flex-start",
  },
  checkboxText: (color) => ({
    fontFamily: fonts.Medium_Font,
    fontSize: 17,
    lineHeight: 19,
    color: color || '#062D5B',
    marginLeft: 10,
    flex: 1,
  }),
  deleteButton: {
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderTopColor: "#D1D1D1",
    borderBottomColor: "#D1D1D1",
    paddingVertical: 10,
    paddingHorizontal: 25,
    flexDirection: "row",
    alignItems: "center",
    marginTop: 20,
    marginBottom: 20,
  },
  deleteBtnTxt: (color) => ({
    color,
    fontSize: 17,
    lineHeight: 19,
    marginLeft: 10,
    textTransform: "uppercase",
    fontFamily: fonts.Medium_Font,
  }),
  emptyView: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  parentView: {
    alignSelf: "flex-start",
    paddingVertical: 2,
    paddingHorizontal: 15,
    backgroundColor: `rgba(${hexToRgb("#C4C4C4").join(", ")}, 0.7)`,
  },
  parentTxt: {
    fontFamily: fonts.Regular_Font,
    color: "#FFFFFF",
    lineHeight: 14,
    fontSize: 12,
  },
});
