import { StyleSheet, Platform, Dimensions } from "react-native";
import { moderateScale } from "../../styles/utils/utils";

import fonts from "../../theme/fonts";


const { width, height } = Dimensions.get("window");
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  searchContainer: {
    marginTop: 30,
    marginHorizontal: 38,
  },
  scrollContainer: {
    flexGrow: 1,
  },
  eventListScrollContainer: {
    flexGrow: 1,
    paddingVertical: 20,
    paddingLeft: 5, paddingRight: 15,
  },
  eventImage: {
    width: '100%',
  },
  eventImageContainer: {
    flex: 1,
    padding: 10,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    zIndex:99999
  },
  shareButton: {
    alignSelf: "flex-end",
  },
  eventNameContainer: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  eventName: {
    fontFamily: fonts.Bold_Font,
    fontSize: 18,
    lineHeight: 21,
    color: "#fff",
    textTransform: "uppercase",
    marginBottom: 5,
    letterSpacing: 1,
  },
  eventDate: {
    fontFamily: fonts.Regular_Font,
    fontSize: 17,
    lineHeight: 21,
    color: "#fff",
    letterSpacing: 1,
  },
  eventType: {
    height: 40,
    width: 40,
  },
  sponsorLogo: {
    height: 70,
    width: 160,
    marginHorizontal: 10,
  },
  tabViewStyle: {
    marginHorizontal: 10,
  },
  tabSceneContainerStyle: {
    paddingHorizontal: 10,
  },
  tabStyle: {
    height: 55,
    width: "auto",
    marginHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  tabBarStyle: {
    backgroundColor: "transparent",
  },
  tabIndicator: (color) => ({
    borderBottomWidth: 3,
    borderBottomColor: color || "#5086A7",
  }),
  tabText: (color) => ({
    fontFamily: fonts.Bold_Font,
    fontSize: 11,
    lineHeight: 16,
    color: color || "#062D5B",
    letterSpacing: 1,
    textTransform: "uppercase",
  }),
  activeTabText: (color) => ({
    color: color || "#5086A7",
  }),
  tabIconStyle: {
    width: 25,
    height: 25,
    marginBottom: 5,
  },
  infoContainer: {
    flex: 1,
    paddingVertical: 20,
  },
  eventInfoText: {
    fontFamily: fonts.Regular_Font,
    fontSize: 16,
    lineHeight: 18,
    letterSpacing: 1,
    color: "#7E7E7E",
  },
  programContainer: {
    flex: 1,
    paddingVertical: 20,
  },
  programTitleContainer: {
    marginVertical: 10,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  programTitle: {
    fontFamily: fonts.Regular_Font,
    fontSize: 18,
    lineHeight: 21,
    color: "#7E7E7E",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  programDownloadBtn: {
    position: "absolute",
    right: 0,
  },
  seprator: {
    borderTopWidth: 1,
    borderTopColor: "#D1D1D1",
  },
  titleStyle: (color) => ({
    marginTop: 40,
    marginBottom: 10,
    color: color || '#062D5B',
    fontSize: 18,
    lineHeight: 21,
    fontFamily: fonts.Bold_Font,
    marginHorizontal: 15,
    textTransform: "uppercase",
  }),
  buttons: {
    flexDirection: "row",
    alignItems: "center",
  },
  buttonText: (color) => ({
    fontSize: 18,
    color: color || "#062D5B",
    fontFamily: fonts.Bold_Font,
  }),
  eventDetailsContainer: {
    flex: 0.95,
    paddingHorizontal: 15,
  },
  listSeprator: {
    height: 1,
    marginVertical: 15,
    backgroundColor: "#D1D1D1",
  },
  listEventImageContainer: {
    height: 56,
    width: 60,
    overflow: "visible",
    borderRadius: 5,
    backgroundColor: "#fff",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: {
          width: 0,
          height: 5,
        },
        shadowOpacity: 0.27,
        shadowRadius: 4.65,
      },
      android: {
        elevation: 6,
      },
    }),
    marginLeft: 10,
  },
  listEventImageSubContainer: {
    borderRadius: 5,
    overflow: "hidden",
  },
  listEventImage: {
    height: "100%",
    width: "100%",
  },
  sportBadge: (color) => ({
    borderRadius: 3,
    paddingVertical: 2,
    paddingHorizontal: 5,
    alignSelf: "flex-start",
    backgroundColor: color || "#5086A7",
  }),
  sportName: {
    color: "#fff",
    fontSize: 12,
    lineHeight: 14,
    fontFamily: fonts.Bold_Font,
  },
  bookmarkBtn: {
    position: "absolute",
    top: 0,
    right: -7,
  },
  loadingContainer: {
    backgroundColor: "#fff",
  },
  poolsContainer: {
    flex: 1,
    paddingTop: 10,
    paddingBottom: 20,
  },
  poolTitle: {
    fontFamily: fonts.Bold_Font,
    fontSize: 21,
    color: "#7E7E7E",
    marginVertical: 5,
    textAlign: "center",
    textTransform: "uppercase",
  },
  poolNameContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    paddingVertical: 10,
    borderBottomColor: "#D1D1D1",
    justifyContent: "space-between",
  },
  activePoolNameContainer: {
    borderBottomWidth: 0,
  },
  poolContentContainer: {},
  poolName: (color) => ({
    fontFamily: fonts.Medium_Font,
    fontSize: 18,
    color: color || "#062D5B",
    marginVertical: 9,
    textAlign: "center",
  }),
  cardContainer: {
    padding: 9,
    borderBottomWidth: 1,
    borderBottomColor: "#D1D1D1",
  },
  documentTitle: (color) => ({
    color: color || '#062D5B',
    fontSize: 18,
    lineHeight: 21,
    fontFamily: fonts.Bold_Font,
    textTransform: "uppercase",
  }),
  docLink: {
    alignSelf: "flex-start",
  },
  documentName: {
    color: '#7E7E7E',
    fontSize: 16,
    lineHeight: 29,
    fontFamily: fonts.Regular_Font,
    textDecorationStyle: "dotted",
    textDecorationLine: "underline",
  },
  titleIndicator: (color) => ({
    width: "20%",
    borderWidth: 1,
    marginVertical: 10,
    borderColor: color || "#062D5B",
  }),
  streamContainer: {
    flex: 1,
    paddingVertical: 20,
  },
  streamLinkBtn: (backgroundColor) => ({
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    backgroundColor,
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 10,
    overflow: "hidden",
  }),
  streamLinkBtnTxt: {
    color: "#FFF",
    fontSize: 16,
    lineHeight: 29,
    marginLeft: 10,
    fontFamily: fonts.Regular_Font,
  },
  headerPointBox: {
    flex: 0.1,
    borderWidth: 1,
    height: "100%",
    paddingVertical: 3,
    alignItems: "center",
    borderColor: "#D1D1D1",
  },
  poolsTableHeaderContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerPointBoxText: {
    color: "#7E7E7E",
    fontSize: 14,
    lineHeight: 17,
    fontFamily: fonts.Medium_Font,
  },
  photoStyle: {
    width: width - 40,
    height: width * 0.4,
    marginVertical: 5,
    justifyContent: "flex-end",
    padding: 10,
    borderRadius: 10,
  },
  photoDescription: (color) => ({
    color: "#7E7E7E",
    fontSize: 16,
    lineHeight: 20,
    fontFamily: fonts.Medium_Font,
  }),
  imageUploaderModalContainer: {
    flex: 1,
    justifyContent: "flex-end",
  },
  imageUploaderModalSubContainer: {
    padding: 20,
    maxHeight: height * 0.8,
    backgroundColor: "#fff",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: {
          width: 0,
          height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
      },
      android: {
        elevation: 5,
      },
    }),
  },
  imageUploaderHandleView: {
    height: 6,
    width: "25%",
    borderRadius: 5,
    alignSelf: "center",
    backgroundColor: "#C4C4C4",
  },
  imageUploaderContainerTitle: {
    color: "#7E7E7E",
    fontFamily: fonts.Bold_Font,
    fontSize: 18,
    lineHeight: 21,
    alignSelf: "center",
    letterSpacing: 1,
    marginVertical: 20,
  },
  closeButton: {
    position: "absolute",
    top: 15,
    right: 20,
  },
  imageViewContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingBottom: 10,
  },
  imagePreview: {
    width: 100,
    height: 100,
    borderRadius: 2,
    marginRight: 10,
  },
  imageUploadDescriptioonBox: {
    flex: 1,
    height: 100,
    borderWidth: 1,
    borderRadius: 2,
    paddingHorizontal: 5,
    borderColor: "#D1D1D1",
  },
  imageDescriptionInput: {
    flex: 1,
    height: "100%",
    color: "#000",
    textAlignVertical: "top",
  },
  imageUploadButton: (color) => ({
    height: 40,
    width: "48%",
    borderRadius: 5,
    marginBottom: 10,
    alignItems: 'center',
    justifyContent: "center",
    backgroundColor: color || "#5086A7",
  }),
  imageUploadButtonText: {
    fontSize: 18,
    lineHeight: 21,
    letterSpacing: 1,
    color: "#FFFFFF",
    fontFamily: fonts.Medium_Font,
  },
  imageUploadButtonContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  imageUploadCancelButton: (color) => ({
    borderWidth: 1,
    borderColor: color || "#5086A7",
    backgroundColor: "transparent",
  }),
  imageUploadCancelButtonText: (color) => ({
    color: color || "#5086A7",
  }),
  imageShareBtn: {
    flexDirection: "row",
    alignItems: "center",
  },
  imageShareBtnTxt: {
    fontSize: 16,
    color: "#fff",
    fontFamily: fonts.Bold_Font,
  },
  imageViewFooterMainContainer: {
    width: "100%",
    paddingHorizontal: 10,
  },
  imageViewFooterSubContainer: {
  },
  imageViewFooterButtonContainer: {
    marginTop: 10,
    alignItems: "center",
    flexDirection: "row-reverse",
    justifyContent: "space-between",
  },
  imageCaption: {
    fontSize: 14,
    color: "#fff",
    lineHeight: 16,
    fontFamily: fonts.Regular_Font,
  },
  repView: {
    alignItems: "center",
    paddingBottom: 15,
  },
  repType: {
    fontFamily: fonts.Regular_Font,
    fontSize: 19,
    lineHeight: 22,
    letterSpacing: 1,
    color: "#404041",
    marginBottom: 10,
  },
  repLabel: {
    fontFamily: fonts.Bold_Font,
    fontSize: 16,
    lineHeight: 18,
    letterSpacing: 1,
    color: "#404041",
  },
  repValue: {
    fontFamily: fonts.Regular_Font,
    color: "#7E7E7E",
  },
  extraInfoBox: {
    padding: 10,
    alignItems: "center",
  },
  extraInfoBoxTitle: {
    fontFamily: fonts.Medium_Font,
    fontSize: 19,
    lineHeight: 22,
    color: "#404041",
    marginBottom: 15,
    textTransform: "uppercase",
  },
  extraInfoBoxDescription: {
    fontFamily: fonts.Regular_Font,
    fontSize: 16,
    color: "#404041",
    textAlign: "left",
    paddingHorizontal: 20,
    lineHeight: 18,
  },
  playerNameContainer: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#D1D1D1",
  },
  playerNameContainer2: {
    justifyContent: "space-between",
    borderBottomColor: "#D1D1D1",
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    paddingVertical: 10,
  },
  playerName: {
    fontFamily: fonts.Regular_Font,
    fontSize: 15,
    lineHeight: 17,
    color: "#7E7E7E",
    letterSpacing: 1,
  },
  centerView: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },

  header: (backgroundColor) => ({
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: backgroundColor || '#062D5B',
    overflow: 'hidden',
  }),
  imageContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    width: null,
  },
  bar: {
    height: 100,
    marginTop: 28,
    backgroundColor: 'transparent',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
  },
  barTitle: {
    fontFamily: fonts.Bold_Font,
    fontSize: 18,
    lineHeight: 21,
    color: "#fff",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 10,
    textAlign: "center",
    marginHorizontal: 10,
  },
  title: {
    fontFamily: fonts.Bold_Font,
    fontSize: 18,
    lineHeight: 21,
    color: "#fff",
    textTransform: "uppercase",
    marginBottom: 5,
    letterSpacing: 1,
  },
  resultContainer: (color) => ({
    paddingVertical: 15,
    borderBottomWidth: 2,
    borderBottomColor: color || "#5086A7",
  }),
  studentName: (color) => ({
    fontFamily: fonts.Bold_Font,
    fontSize: 15,
    lineHeight: 17,
    color: color || "#5086A7",
    letterSpacing: 1,
    marginBottom: 5,
  }),
  lblStyl: {
    color: "#7E7E7E",
    fontFamily: fonts.Bold_Font,
    fontSize: 15,
    lineHeight: 17,
    letterSpacing: 1,
    marginBottom: 5,
  },
  resultDataContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  studentSeprator: {
    marginTop: 5,
    marginBottom: 10,
    borderTopWidth: 1,
    borderTopColor: "#D1D1D1",
  },
  headlineContainer: {
    paddingTop: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  titleSponsorsContainer: {
    width: "100%",
    backgroundColor: "#fff",
  },
  sponsorDataContainer: {
    paddingVertical: 10,
  },
  sponsorTitle: (color) => ({
    fontSize: 19,
    lineHeight: 24,
    color: color || '#062D5B',
    fontFamily: fonts.Bold_Font,
  }),
  sponsorSlogan: (color) => ({
    fontSize: 17,
    lineHeight: 20,
    color: color || '#062D5B',
    fontFamily: fonts.Medium_Font,
  }),
  sponsorDescription: {
    marginTop: 5,
    fontSize: 13,
    color: "#7E7E7E",
    fontFamily: fonts.Regular_Font,
  },
  sponsorLinkLbl: {
    marginTop: 5,
    fontSize: 15,
    color: "#7E7E7E",
    fontFamily: fonts.Regular_Font,
  },
  sponsorLink: (color) => ({
    color,
    fontFamily: fonts.Bold_Font,
  }),
  scrollLeftRightIcon: {
    height: 30,
    width: 30,
    marginHorizontal: 5,
  },
  tabScrollContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  statByContainer: (backgroundColor) => ({
    paddingVertical: 5,
    paddingHorizontal: 10,
    alignItems: "center",
    backgroundColor,
    marginVertical: 10,
  }),
  statByTxt: {
    fontSize: 15,
    color: "#FFFFFF",
    fontFamily: fonts.Regular_Font,
  },
  statPlayerName: {
    fontFamily: fonts.Regular_Font,
    fontSize: 15,
    lineHeight: 17,
    color: "#404041",
    letterSpacing: 1,
  },
  statPlayerTeamName: {
    fontFamily: fonts.Regular_Font,
    fontSize: 13,
    lineHeight: 15,
    color: "#404041",
    letterSpacing: 1,
    marginTop: 5,
  },
  placingmainContainerStyle: {
    marginHorizontal: 20,
    alignItems: "center",
  },
  placingFirstStyle: backgroundColor => ({
    width: 120,
    height: 120,
    borderRadius: 120 / 2,
    backgroundColor,
    elevation: 5,
    zIndex: 5,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#ec1c24',
    ...Platform.select({
      ios: {
        shadowOffset: { width: 0, height: 3 },
        shadowRadius: 5,
        shadowOpacity: 0.2,
      },
      android: {
        elevation: 5,
      },
    }),
  }),
  placingFirstStyleInner: backgroundColor => ({
    width: 100,
    height: 100,
    borderRadius: 100 / 2,
    backgroundColor,
    elevation: 5,
    borderColor: '#fff',
    borderWidth: 0.5,
    zIndex: 5,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#ec1c24',
    ...Platform.select({
      ios: {
        shadowOffset: { width: 0, height: 3 },
        shadowRadius: 5,
        shadowOpacity: 0.2,
      },
      android: {
        elevation: 5,
      },
    }),
  }),
  placingFirstTextStyle: {
    fontSize: 30,
    lineHeight: 35,
    color: '#ffffff',
    fontFamily: fonts.Regular_Font,
    textAlign: 'center',
  },
  textPlayerName: (fontSize, lineHeight) => ({
    color: '#404041',
    width: '95%',
    fontFamily: fonts.Regular_Font,
    textAlign: 'center',
    margin: 5,
    fontSize,
    lineHeight,
  }),

  placingMiddleStyleContainer: {
    width: '100%',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginTop: 20,
  },

  placingMiddleStyle: (alignSelf) => ({
    width: 90,
    height: 90,
    borderRadius: 90 / 2,
    backgroundColor: '#ffffff',
    elevation: 5,
    zIndex: 5,
    alignSelf,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#666666',
  }),

  placingMiddleTextStyle: {
    fontSize: 21,
    lineHeight: 25,
    color: '#000000',
    fontFamily: fonts.Regular_Font,
  },
  placingEndStyleContainer: {
    width: '100%',
    alignItems: 'center',
    marginTop: 30,
  },
  placingTableStyle: borderColor => ({
    width: '100%',
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor,
    flexDirection: 'row',

  }),
  placingTableColum1: borderColor => ({
    width: '35%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderColor,
  }),
  placingTableColum2: {
    width: '65%',
    alignItems: 'center',
    justifyContent: 'center',

  },
  tableSeparator: borderColor => ({
    width: '100%',
    borderBottomWidth: 1,
    borderColor,
    marginBottom: 15,
  }),
  readMoreButtonStyle: backgroundColor => ({
    backgroundColor,
    alignSelf: 'flex-start',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 4,
  }),
  readMoreButtonTextStyle: {
    color: '#FFFFFF',
    fontFamily: fonts.Regular_Font,
    textAlign: 'center',
    fontSize: moderateScale(12),
  },
  titleSponsorLogo: {
    width: 160,
    marginHorizontal: 10,
  },
});
