import { StyleSheet } from "react-native";
import * as hFunctions from "../../services/helperFunctions";
import fonts from "../../theme/fonts";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  scrollContainer: {
    flexGrow: 1,
  },
  gameImage: (height) => ({
    width: '100%',
    height,
    // flexDirection: "row",
    // justifyContent: "center"
  }),
  teamScoreView: {
    flex: 0.5,
    height: "100%",
    paddingVertical: 10,
    paddingHorizontal: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  team1ScoreView: (color) => {
    const bgColor = `rgba(${hFunctions.hexToRgb(color || '#062D5B').join(", ")}, 0.4)`;
    return {
      flex: 1,
      flexDirection: 'row',
      justifyContent: 'center',
      backgroundColor: bgColor || "rgba(80, 134, 167, 0.6);",
    };
  },
  scoreText: {
    fontSize: 55,
    lineHeight: 75,
    letterSpacing: 1,
    color: "#FFFFFF",
    textTransform: "uppercase",
    fontFamily: fonts.Bold_Font,
  },
  periodView: (color) => {
    const bgColor = `rgba(${hFunctions.hexToRgb(color || '#062D5B').join(", ")}, 0.4)`;

    return {
      padding: 5,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: bgColor || "rgba(6, 45, 91, 0.7);",
    };
  },
  periodText: {
    fontSize: 18,
    color: "#FFFFFF",
    textAlign: 'center',
    fontFamily: fonts.Medium_Font,
  },
  aniPeriodView: {
    borderBottomStartRadius: 10,
    borderBottomEndRadius: 10,
    backgroundColor: "#F5F5F5",
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  aniPeriodText: {
    fontSize: 18,
    color: "#7E7E7E",
    textAlign: 'center',
    fontFamily: fonts.Medium_Font,
  },
  aniScoreText: {
    fontFamily: fonts.Bold_Font,
    fontSize: 18,
    color: "#FFFFFF",
    textTransform: "uppercase",
    textAlign: 'center',
    padding: 2,
  },
  teamNameBox: {
    position: "absolute",
    bottom: 15,
    paddingVertical: 2,
    borderRadius: 8,
    paddingHorizontal: 13,
    backgroundColor: "#fff",
  },
  teamName: {
    fontSize: 18,
    lineHeight: 21,
    letterSpacing: 1,
    color: "#7E7E7E",
    textAlign: "center",
    textTransform: "uppercase",
    fontFamily: fonts.Bold_Font,
  },
  aniTeamName: {
    fontFamily: fonts.Bold_Font,
    fontSize: 15,
    letterSpacing: 1,
    color: "#FFFFFF",
    textAlign: "center",
    textTransform: "uppercase",
    paddingHorizontal: 5,
  },
  shareButton: {
    position: "absolute",
    top: 15,
    right: 10,
  },
  triangle: {
    position: "absolute",
    transform: [{ rotate: "180deg" }],
    width: 0,
    height: 0,
    backgroundColor: "transparent",
    borderStyle: "solid",
    borderLeftWidth: 60,
    borderRightWidth: 60,
    borderBottomWidth: 100,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderBottomColor: "#fff",
  },
  vsText: (color) => ({
    position: "absolute",
    fontFamily: fonts.Bold_Font,
    fontSize: 36,
    lineHeight: 42,
    letterSpacing: 1,
    color: color || "#062D5B",
  }),
  statusBox: {
    borderWidth: 1,
    borderColor: "#D1D1D1",
    borderBottomStartRadius: 10,
    borderBottomEndRadius: 10,
    backgroundColor: "#F5F5F5",
    paddingHorizontal: 20,
    paddingVertical: 5,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  statusText: {
    fontFamily: fonts.Bold_Font,
    fontSize: 18,
    lineHeight: 21,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: "#7E7E7E",
  },
  tabViewStyle: {
    marginTop: 20,
  },
  tabSceneContainerStyle: {
    paddingBottom: 20,
  },
  tabStyle: {
    height: 55,
    width: "auto",
    marginHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  tabBarStyle: {
    backgroundColor: "transparent",
    marginHorizontal: 10,
  },
  tabText: (color) => ({
    fontFamily: fonts.Bold_Font,
    fontSize: 11,
    lineHeight: 16,
    color: color || "#062D5B",
    letterSpacing: 1,
    textTransform: "uppercase",
  }),
  activeTabText: (color) => ({
    color: color || "#5086A7",
  }),
  tabIndicator: (color) => ({
    borderBottomWidth: 3,
    alignSelf: "center",
    borderColor: color || "#5086A7",
  }),
  commentryBox: {
    padding: 10,
    flexDirection: "row",
    backgroundColor: "#fff",
    alignItems: "center",
  },
  commentryheading: (color) => ({
    fontFamily: fonts.Regular_Font,
    fontSize: 17,
    lineHeight: 19,
    letterSpacing: 1,
    color: color || "#062D5B",
    marginBottom: 5,
    textTransform: "uppercase",
  }),
  commentryText: {
    fontFamily: fonts.Regular_Font,
    fontSize: 14,
    lineHeight: 16,
    letterSpacing: 1,
    color: "#7E7E7E",
    textTransform: "uppercase",
    marginBottom: 5,
  },
  statsContainer: {
    flex: 1,
    marginTop: 20,
    paddingTop: 20,
    paddingHorizontal: 15,
  },
  goalsView: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    backgroundColor: "#F5F5F5",
    borderRadius: 6,
  },
  goalText: {
    fontFamily: fonts.Bold_Font,
    fontSize: 18,
    lineHeight: 21,
    letterSpacing: 1,
    color: "#726F6F",
    textTransform: "uppercase",
  },
  statsTitle: (color) => ({
    fontFamily: fonts.Medium_Font,
    fontSize: 13,
    lineHeight: 15,
    letterSpacing: 1,
    color: color || "#5086A7",
    textTransform: "uppercase",
    alignSelf: "center",
    textAlign: "center",
    marginVertical: 15,
  }),
  teamStateContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  teamDataContainer: {
    flex: 0.49,
    minHeight: 50,
    paddingRight: 10,
    justifyContent: "center",
  },
  teamDataRightContainer: {
    flex: 0.49,
    alignItems: "flex-end",
    paddingBottom: 10,
    paddingLeft: 10,
  },
  statsText: {
    fontFamily: fonts.Regular_Font,
    fontSize: 13,
    lineHeight: 15,
    letterSpacing: 1,
    color: "#7E7E7E",
    textTransform: "uppercase",
  },
  statsSepratorStyle: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#E5E5E5",
    height: "100%",
    overflow: "visible",
  },
  pointerStyle: (color) => ({
    position: "absolute",
    left: -4,
    height: 7,
    width: 9,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: color || "#5086A7",
  }),
  topPointer: (color) => ({
    top: 0,
    backgroundColor: color || "#5086A7",
  }),
  bottomPointer: {
    bottom: 0,
  },
  upcommingGamesContainer: {
    flex: 1,
    paddingTop: 10,
    paddingHorizontal: 15,
  },
  loadingContainer: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    zIndex: 100,
  },
  commentImgContainer: {
    width: 45,
    height: 45,
    marginRight: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  commentImage: {
    width: "50%",
    height: "50%",
  },
  commentryHeadingBox: (color) => ({
    paddingVertical: 2,
    paddingHorizontal: 10,
    alignItems: "flex-end",
    backgroundColor: color || "#062D5B",
  }),
  commentryHeadingText: {
    fontSize: 45,
    textTransform: "uppercase",
    fontFamily: fonts.Regular_Font,
    color: "rgba(255, 255, 255, 0.2)",
  },
  playerStatsContainer: {
    flex: 1,
    paddingTop: 20,
  },
  playerStateContainer: {
    width: "50%",
    minHeight: 55,
  },
  playerStyle: (index, ind) => ({
    backgroundColor: ind % 2 === 0 ? "transparent" : "#F5F5F5",
    padding: 10,
    width: "100%",
    // alignItems: index % 2 == 0 ? "flex-end" : "flex-start",
    borderRightWidth: index % 2 == 0 ? 0.5 : 0,
    borderLeftWidth: index % 2 == 0 ? 0 : 0.5,
    borderColor: "#D1D1D1",
  }),
  playerName: {
    fontFamily: fonts.Regular_Font,
    fontSize: 13,
    lineHeight: 15,
    letterSpacing: 1,
    color: "#7E7E7E",
    marginBottom: 5,
  },
  statsIconContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    minHeight: 15,
  },
  statsIcon: {
    height: 13,
    width: 13,
    marginHorizontal: 2.5,
    marginBottom: 2.5,
  },
  teamLblView: (type) => {
    const backgroundColor = type === "Blue" ? "#007FCD" : type === "White" ? "white" : "transparent";
    return {
      top: 0,
      paddingVertical: 2,
      paddingHorizontal: 7,
      backgroundColor,
      borderRadius: 2,
      position: "absolute",
    };
  },
  teamLblViewText: (type) => {
    const color = type === "Blue" ? "#E5E5E5" : type === "White" ? "#7E7E7E" : "transparent";
    return {
      color,
    };
  },
  footerContainer: {
    padding: 10,
  },
  footerTitleContainer: (backgroundColor) => ({
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 5,
    backgroundColor,
    marginBottom: 10,
  }),
  footerTitleTxt: {
    fontFamily: fonts.Bold_Font,
    fontSize: 18,
    lineHeight: 21,
    color: "#FFFFFF",
  },
  keyDataContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  keyIcon: {
    height: 20,
    width: 20,
  },
  keyName: {
    fontFamily: fonts.Regular_Font,
    fontSize: 16,
    lineHeight: 17,
    color: "#000",
    marginLeft: 10,
  },
  tabIconStyle: {
    width: 25,
    height: 25,
    marginBottom: 5,
    alignSelf: "center",
  },
  leftRightBtn: {
    backgroundColor: "#FFFFFF",
    position: "absolute",
    top: 20,
    height: 71,
    justifyContent: "center",
  },
  positionLeft: {
    left: 0,
  },
  positionRight: {
    right: 0,
  },
  scrollLeftRightIcon: {
    height: 30,
    width: 30,
    marginHorizontal: 5,
  },
  staffContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  tabScrollContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  header: (backgroundColor) => ({
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: backgroundColor || '#062D5B',
    overflow: 'hidden',
  }),
  imageContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    width: null,
  },
  bar: {
    height: 150,
    // marginTop: 28,
    marginTop: 10,
    position: 'absolute',
    backgroundColor: 'transparent',
    top: 0,
    left: 0,
    right: 0,
  },
  barTitle: {
    fontFamily: fonts.Bold_Font,
    fontSize: 18,
    lineHeight: 21,
    color: "#fff",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 10,
    textAlign: "center",
    marginHorizontal: 10,
  },
  aniHD: {
    width: 0.5,
    marginVertical: 5,
    backgroundColor: '#ffffff',
  },
  aniVD: {
    height: 0.5,
    marginVertical: 3,
    marginHorizontal: 10,
    backgroundColor: '#ffffff',
  },
  aniScoreView: {
    flex: 1,
    alignSelf: 'center',
  },
  teamTitle: {
    fontSize: 12,
    color: '#7E7E7E',
    fontWeight: '600',
    marginBottom:10
  },
  scoreContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '90%',
    alignSelf: 'center',
    marginTop: 25,
  },
  scoreInput: {
    height: 85,
    width: '72%',
    paddingHorizontal: '5%',
    borderRadius: 12,
    backgroundColor: '#fff',
    borderWidth: 0.3,
    borderColor: '#7E7E7E',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
